<?php
/**
 * @file
 * dva_taxonomies.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function dva_taxonomies_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'Supplements',
    'description' => '',
    'format' => 'raw',
    'weight' => 0,
    'uuid' => '0b1884f7-581e-4f19-8cf8-bcd58c428339',
    'vocabulary_machine_name' => 'dva_services',
    'metatags' => array(
      'und' => array(
        'AGLSTERMS.act' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.aggregationLevel' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.availability' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.case' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.category' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.dateLicenced' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.documentType' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.function' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.isBasisFor' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.isBasedOn' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.jurisdiction' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.mandate' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.protectiveMarking' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.regulation' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.serviceType' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'robots' => array(
          'value' => array(
            'index' => 0,
            'follow' => 0,
            'noindex' => 0,
            'nofollow' => 0,
            'noarchive' => 0,
            'nosnippet' => 0,
            'noodp' => 0,
            'noydir' => 0,
            'noimageindex' => 0,
            'notranslate' => 0,
          ),
        ),
        'dcterms.title' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.creator' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.subject' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.description' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.publisher' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.contributor' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.date' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.type' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.format' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.identifier' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.source' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.language' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.relation' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.coverage' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.rights' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'VetAffairs',
    'description' => '',
    'format' => 'raw',
    'weight' => 0,
    'uuid' => '400e1f83-d1dc-4c7a-8dce-564683638b71',
    'vocabulary_machine_name' => 'news_article_type',
    'metatags' => array(
      'und' => array(
        'AGLSTERMS.act' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.aggregationLevel' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.availability' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.case' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.category' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.dateLicenced' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.documentType' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.function' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.isBasisFor' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.isBasedOn' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.jurisdiction' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.mandate' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.protectiveMarking' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.regulation' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.serviceType' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'robots' => array(
          'value' => array(
            'index' => 0,
            'follow' => 0,
            'noindex' => 0,
            'nofollow' => 0,
            'noarchive' => 0,
            'nosnippet' => 0,
            'noodp' => 0,
            'noydir' => 0,
            'noimageindex' => 0,
            'notranslate' => 0,
          ),
        ),
        'dcterms.title' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.creator' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.subject' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.description' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.publisher' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.contributor' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.date' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.type' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.format' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.identifier' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.source' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.language' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.relation' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.coverage' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.rights' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Rehab@DVA',
    'description' => '',
    'format' => 'raw',
    'weight' => 0,
    'uuid' => '4c3c726a-bfc4-4578-a243-b985c73e8abe',
    'vocabulary_machine_name' => 'news_article_type',
    'metatags' => array(
      'und' => array(
        'AGLSTERMS.act' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.aggregationLevel' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.availability' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.case' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.category' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.dateLicenced' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.documentType' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.function' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.isBasisFor' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.isBasedOn' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.jurisdiction' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.mandate' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.protectiveMarking' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.regulation' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.serviceType' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'robots' => array(
          'value' => array(
            'index' => 0,
            'follow' => 0,
            'noindex' => 0,
            'nofollow' => 0,
            'noarchive' => 0,
            'nosnippet' => 0,
            'noodp' => 0,
            'noydir' => 0,
            'noimageindex' => 0,
            'notranslate' => 0,
          ),
        ),
        'dcterms.title' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.creator' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.subject' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.description' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.publisher' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.contributor' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.date' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.type' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.format' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.identifier' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.source' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.language' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.relation' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.coverage' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.rights' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Insurance and Loans',
    'description' => '',
    'format' => 'raw',
    'weight' => 0,
    'uuid' => '83d1359d-0a96-4e84-9f2a-f79d2e8755c6',
    'vocabulary_machine_name' => 'dva_services',
    'metatags' => array(
      'und' => array(
        'AGLSTERMS.act' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.aggregationLevel' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.availability' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.case' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.category' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.dateLicenced' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.documentType' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.function' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.isBasisFor' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.isBasedOn' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.jurisdiction' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.mandate' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.protectiveMarking' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.regulation' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.serviceType' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'robots' => array(
          'value' => array(
            'index' => 0,
            'follow' => 0,
            'noindex' => 0,
            'nofollow' => 0,
            'noarchive' => 0,
            'nosnippet' => 0,
            'noodp' => 0,
            'noydir' => 0,
            'noimageindex' => 0,
            'notranslate' => 0,
          ),
        ),
        'dcterms.title' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.creator' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.subject' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.description' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.publisher' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.contributor' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.date' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.type' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.format' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.identifier' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.source' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.language' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.relation' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.coverage' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.rights' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'DVA News',
    'description' => '',
    'format' => 'raw',
    'weight' => 0,
    'uuid' => '84a6f13f-8525-466c-ad34-1f3daf4bcf66',
    'vocabulary_machine_name' => 'news_article_type',
    'metatags' => array(
      'und' => array(
        'AGLSTERMS.act' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.aggregationLevel' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.availability' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.case' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.category' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.dateLicenced' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.documentType' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.function' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.isBasisFor' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.isBasedOn' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.jurisdiction' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.mandate' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.protectiveMarking' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.regulation' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.serviceType' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'robots' => array(
          'value' => array(
            'index' => 0,
            'follow' => 0,
            'noindex' => 0,
            'nofollow' => 0,
            'noarchive' => 0,
            'nosnippet' => 0,
            'noodp' => 0,
            'noydir' => 0,
            'noimageindex' => 0,
            'notranslate' => 0,
          ),
        ),
        'dcterms.title' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.creator' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.subject' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.description' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.publisher' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.contributor' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.date' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.type' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.format' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.identifier' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.source' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.language' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.relation' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.coverage' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.rights' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Provider News',
    'description' => '',
    'format' => 'raw',
    'weight' => 0,
    'uuid' => 'aa65af34-49b3-45fd-a674-781bfb13e95f',
    'vocabulary_machine_name' => 'news_article_type',
    'metatags' => array(
      'und' => array(
        'AGLSTERMS.act' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.aggregationLevel' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.availability' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.case' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.category' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.dateLicenced' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.documentType' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.function' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.isBasisFor' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.isBasedOn' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.jurisdiction' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.mandate' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.protectiveMarking' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.regulation' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.serviceType' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'robots' => array(
          'value' => array(
            'index' => 0,
            'follow' => 0,
            'noindex' => 0,
            'nofollow' => 0,
            'noarchive' => 0,
            'nosnippet' => 0,
            'noodp' => 0,
            'noydir' => 0,
            'noimageindex' => 0,
            'notranslate' => 0,
          ),
        ),
        'dcterms.title' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.creator' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.subject' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.description' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.publisher' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.contributor' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.date' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.type' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.format' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.identifier' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.source' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.language' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.relation' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.coverage' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.rights' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Media release',
    'description' => '',
    'format' => 'raw',
    'weight' => 0,
    'uuid' => 'b34ef4a4-1480-444d-8b76-03bbd67c5233',
    'vocabulary_machine_name' => 'news_article_type',
    'metatags' => array(
      'und' => array(
        'AGLSTERMS.act' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.aggregationLevel' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.availability' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.case' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.category' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.dateLicenced' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.documentType' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.function' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.isBasisFor' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.isBasedOn' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.jurisdiction' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.mandate' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.protectiveMarking' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.regulation' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.serviceType' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'robots' => array(
          'value' => array(
            'index' => 0,
            'follow' => 0,
            'noindex' => 0,
            'nofollow' => 0,
            'noarchive' => 0,
            'nosnippet' => 0,
            'noodp' => 0,
            'noydir' => 0,
            'noimageindex' => 0,
            'notranslate' => 0,
          ),
        ),
        'dcterms.title' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.creator' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.subject' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.description' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.publisher' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.contributor' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.date' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.type' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.format' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.identifier' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.source' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.language' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.relation' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.coverage' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.rights' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Home Care',
    'description' => '',
    'format' => 'raw',
    'weight' => 0,
    'uuid' => 'ba91a94f-9a14-4623-a708-69aca646379a',
    'vocabulary_machine_name' => 'dva_services',
    'metatags' => array(
      'und' => array(
        'AGLSTERMS.act' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.aggregationLevel' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.availability' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.case' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.category' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.dateLicenced' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.documentType' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.function' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.isBasisFor' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.isBasedOn' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.jurisdiction' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.mandate' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.protectiveMarking' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.regulation' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.serviceType' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'robots' => array(
          'value' => array(
            'index' => 0,
            'follow' => 0,
            'noindex' => 0,
            'nofollow' => 0,
            'noarchive' => 0,
            'nosnippet' => 0,
            'noodp' => 0,
            'noydir' => 0,
            'noimageindex' => 0,
            'notranslate' => 0,
          ),
        ),
        'dcterms.title' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.creator' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.subject' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.description' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.publisher' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.contributor' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.date' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.type' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.format' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.identifier' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.source' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.language' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.relation' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.coverage' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.rights' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Men\'s Health Peer Education',
    'description' => '',
    'format' => 'raw',
    'weight' => 0,
    'uuid' => 'c312d53c-7690-4fbf-95d7-a5fb72dd5e23',
    'vocabulary_machine_name' => 'news_article_type',
    'metatags' => array(
      'und' => array(
        'AGLSTERMS.act' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.aggregationLevel' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.availability' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.case' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.category' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.dateLicenced' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.documentType' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.function' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.isBasisFor' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.isBasedOn' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.jurisdiction' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.mandate' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.protectiveMarking' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.regulation' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.serviceType' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'robots' => array(
          'value' => array(
            'index' => 0,
            'follow' => 0,
            'noindex' => 0,
            'nofollow' => 0,
            'noarchive' => 0,
            'nosnippet' => 0,
            'noodp' => 0,
            'noydir' => 0,
            'noimageindex' => 0,
            'notranslate' => 0,
          ),
        ),
        'dcterms.title' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.creator' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.subject' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.description' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.publisher' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.contributor' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.date' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.type' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.format' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.identifier' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.source' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.language' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.relation' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.coverage' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.rights' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Medical',
    'description' => '',
    'format' => 'raw',
    'weight' => 0,
    'uuid' => 'f7b49e02-f18d-4b17-b8cc-fd08f69d69a6',
    'vocabulary_machine_name' => 'dva_services',
    'metatags' => array(
      'und' => array(
        'AGLSTERMS.act' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.aggregationLevel' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.availability' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.case' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.category' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.dateLicenced' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.documentType' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.function' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.isBasisFor' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.isBasedOn' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.jurisdiction' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.mandate' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.protectiveMarking' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.regulation' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'AGLSTERMS.serviceType' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'robots' => array(
          'value' => array(
            'index' => 0,
            'follow' => 0,
            'noindex' => 0,
            'nofollow' => 0,
            'noarchive' => 0,
            'nosnippet' => 0,
            'noodp' => 0,
            'noydir' => 0,
            'noimageindex' => 0,
            'notranslate' => 0,
          ),
        ),
        'dcterms.title' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.creator' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.subject' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.description' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.publisher' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.contributor' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.date' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.type' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.format' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.identifier' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.source' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.language' => array(
          'item' => array(
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.relation' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.coverage' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
        'dcterms.rights' => array(
          'item' => array(
            'value' => '',
            'scheme' => '',
            'lang' => '',
            'dir' => 0,
          ),
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  );
  return $terms;
}
